# Generated by Django 3.2.3 on 2021-05-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_genres',
            field=models.ManyToManyField(related_name='like_users', to='movies.Genre'),
        ),
    ]
