# Generated by Django 3.2 on 2021-05-24 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_alter_review_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
